swagger: "2.0"
info:
  description: "This is a specification for DoctorBooking Api. You can find out more about this application at [htp://allaroundjava.com](http://allaroundjava.com)"
  version: "1.0"
  title: "Doctor Booking Application"
  contact:
    email: "adam@allaroundjava.com"
host: "localhost"
basePath: "/v2/doctor-booking"
tags:
- name: "doctors"
  description: "Everything about Doctors in the system"
schemes:
- "http"
paths:
  /doctors:
    post:
      tags:
      - "doctors"
      summary: "Add a new doctor to Medical Clinic"
      description: ""
      operationId: "createDoctor"
      consumes:
      - "application/xml"
      produces:
      - "application/xml"
      parameters:
      - in: "body"
        name: "doctorDto"
        description: "Doctor object that needs to be added to the clinic"
        required: true
        schema:
          $ref: "#/definitions/DoctorDto"
      responses:
        200:
          description: "Created Doctor"
          schema:
            $ref: "#/definitions/DoctorDto"
        405:
          description: "Invalid input"
  /doctors/{id}:
    get:
      tags:
      - "doctors"
      summary: "Retrieve existing doctor information"
      description: ""
      operationId: "getDoctor"
      consumes:
      - "application/xml"
      produces:
      - "application/xml"
      parameters:
      - in: "path"
        name: "id"
        description: "Id of doctor that needs to be retrieved"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
            description: "Successfully retrieved Doctor"
            schema:
              $ref: "#/definitions/DoctorDto"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Doctor with specified ID not found"
definitions:
  DoctorDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      entityId:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Order"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"